"""added is_active

Revision ID: 53f0c6be4bea
Revises: d27a7ccc0b06
Create Date: 2016-06-09 16:16:03.493413

"""

# revision identifiers, used by Alembic.
revision = '53f0c6be4bea'
down_revision = 'd27a7ccc0b06'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_vouchers_log',
                  sa.Column('is_active',
                            mysql.TINYINT(display_width=3, unsigned=True),
                            nullable=False))
    op.add_column('all_vouchers',
                  sa.Column('is_active',
                            mysql.TINYINT(display_width=3, unsigned=True),
                            nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_vouchers', 'is_active')
    op.drop_column('all_vouchers_log', 'is_active')
    ### end Alembic commands ###
