"""reduced size of criteria, benefits and added blacklist criteria

Revision ID: 6ad24a69e213
Revises: e28f26a063b7
Create Date: 2016-05-10 14:46:02.200384

"""

# revision identifiers, used by Alembic.
revision = '6ad24a69e213'
down_revision = 'e28f26a063b7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('blacklist_criteria_json', sa.VARCHAR(length=2000), nullable=True))
    op.alter_column('rule', 'benefits_json',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('rule', 'criteria_json',
               existing_type=mysql.VARCHAR(length=8000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule', 'criteria_json',
               existing_type=sa.VARCHAR(length=2000),
               type_=mysql.VARCHAR(length=8000),
               existing_nullable=False)
    op.alter_column('rule', 'benefits_json',
               existing_type=sa.VARCHAR(length=1000),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=False)
    op.drop_column('rule', 'blacklist_criteria_json')
    ### end Alembic commands ###
