"""added permissions

Revision ID: 6b236f18ce73
Revises: 53f0c6be4bea
Create Date: 2016-06-10 13:26:56.775407

"""

# revision identifiers, used by Alembic.
revision = '6b236f18ce73'
down_revision = '53f0c6be4bea'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', mysql.BIGINT(), nullable=False, autoincrement=False),
    sa.Column('permission', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_permission'), 'permissions', ['permission'], unique=True)
    op.create_table('agent_permission',
    sa.Column('agent_id', mysql.INTEGER(), nullable=True),
    sa.Column('permission_id', mysql.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['tokens.agent_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], )
    )
    op.create_index('agent_id_permission_id', 'agent_permission', ['agent_id', 'permission_id'], unique=False)
    query = 'INSERT INTO `permissions` (`id`, `permission`) VALUES (4, "apply_voucher"), (3, "check_voucher"), (1, "create_voucher"), (5, "fetch_voucher"),(0, "no_permission_required"), (7, "test"), (6, "update_order_status"), (2, "update_voucher")'
    op.execute(text(query))
    query = 'delete from tokens where agent_id=0'
    op.execute(text(query))
    query = 'INSERT INTO `tokens` (`token`, `agent_id`, `agent_name`, `created_at`, `last_accessed_at`) VALUES ("anonymous", 0, "anonymous", "2016-06-10 13:53:53.000000", "2016-06-10 13:53:53.000000")'
    op.execute(text(query))
    query = 'INSERT INTO `agent_permission` (`agent_id`, `permission_id`) VALUES (0, 1),(0, 2),(0, 5),(0, 6)'
    op.execute(text(query))
    # query = 'INSERT INTO `agent_permission` (`agent_id`, `permission_id`) VALUES (1, 3), (1, 4)'
    # op.execute(text(query))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('agent_id_permission_id', table_name='agent_permission')
    op.drop_table('agent_permission')
    op.drop_index(op.f('ix_permissions_permission'), table_name='permissions')
    op.drop_table('permissions')
    ### end Alembic commands ###
