"""increased column sizes for auto tester

Revision ID: 8b1c01cbd343
Revises: f8bc53fa947f
Create Date: 2016-06-03 22:30:48.133412

"""

# revision identifiers, used by Alembic.
revision = '8b1c01cbd343'
down_revision = 'f8bc53fa947f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_tester', 'body',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('auto_tester', 'prod_response',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('auto_tester', 'staging_response',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_tester', 'staging_response',
               existing_type=sa.VARCHAR(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('auto_tester', 'prod_response',
               existing_type=sa.VARCHAR(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('auto_tester', 'body',
               existing_type=sa.VARCHAR(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    ### end Alembic commands ###
