"""added varchar columns back

Revision ID: 9cf6ddb226bd
Revises: b95751801ca0
Create Date: 2016-06-06 14:52:37.503562

"""

# revision identifiers, used by Alembic.
revision = '9cf6ddb226bd'
down_revision = 'b95751801ca0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_tester', sa.Column('body_varchar', sa.VARCHAR(length=5000), nullable=True))
    op.add_column('auto_tester', sa.Column('prod_response_varchar', sa.VARCHAR(length=5000), nullable=True))
    op.add_column('auto_tester', sa.Column('staging_response_varchar', sa.VARCHAR(length=5000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_tester', 'staging_response_varchar')
    op.drop_column('auto_tester', 'prod_response_varchar')
    op.drop_column('auto_tester', 'body_varchar')
    ### end Alembic commands ###
