"""changed varchar to text

Revision ID: b95751801ca0
Revises: 8b1c01cbd343
Create Date: 2016-06-04 14:41:53.620795

"""

# revision identifiers, used by Alembic.
revision = 'b95751801ca0'
down_revision = '8b1c01cbd343'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_tester', 'body',
               existing_type=sa.VARCHAR(5000),
               type_=sa.TEXT,
               existing_nullable=False,
               nullable=False
                    )
    op.alter_column('auto_tester', 'prod_response',
               existing_type=sa.VARCHAR(5000),
               type_=sa.TEXT,
               existing_nullable=False,
               nullable=False
                    )
    op.alter_column('auto_tester', 'staging_response',
               existing_type=sa.VARCHAR(5000),
               existing_nullable=False,
               type_=sa.TEXT,
               nullable=False
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_tester', 'body',
               existing_type=sa.TEXT,
               type_=sa.VARCHAR(5000),
               existing_nullable=False,
               nullable=False
                    )
    op.alter_column('auto_tester', 'prod_response',
               existing_type=sa.TEXT,
               type_=sa.VARCHAR(5000),
               existing_nullable=False,
               nullable=False
                    )
    op.alter_column('auto_tester', 'staging_response',
               existing_type=sa.TEXT,
               type_=sa.VARCHAR(5000),
               existing_nullable=False,
               nullable=False
                    )
    ### end Alembic commands ###
