"""fixed indexes

Revision ID: cd3c8318ffcb
Revises: 6b236f18ce73
Create Date: 2016-06-10 14:52:07.347233

"""

# revision identifiers, used by Alembic.
revision = 'cd3c8318ffcb'
down_revision = '6b236f18ce73'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'agent_permission_ibfk_2', 'agent_permission', type_='foreignkey')
    op.drop_constraint(u'agent_permission_ibfk_1', 'agent_permission', type_='foreignkey')
    op.drop_index('agent_id_permission_id', table_name='agent_permission')
    op.alter_column('agent_permission', 'agent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('agent_permission', 'permission_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    op.create_foreign_key(u'agent_permission_ibfk_1', 'agent_permission', 'tokens', ['agent_id'], ['agent_id'])
    op.create_foreign_key(u'agent_permission_ibfk_2', 'agent_permission', 'permissions', ['permission_id'], ['id'])
    op.create_index('agent_id_permission_id', 'agent_permission', ['agent_id', 'permission_id'], unique=True)
    op.drop_index(op.f('ix_permissions_permission'), table_name='permissions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_permissions_permission'), 'permissions', ['permission'], unique=True)
    op.drop_constraint(u'agent_permission_ibfk_2', 'agent_permission', type_='foreignkey')
    op.drop_constraint(u'agent_permission_ibfk_1', 'agent_permission', type_='foreignkey')
    op.drop_index('agent_id_permission_id', table_name='agent_permission')
    op.alter_column('agent_permission', 'permission_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.alter_column('agent_permission', 'agent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(u'agent_permission_ibfk_1', 'agent_permission', 'tokens', ['agent_id'], ['agent_id'])
    op.create_foreign_key(u'agent_permission_ibfk_2', 'agent_permission', 'permissions', ['permission_id'], ['id'])
    op.create_index('agent_id_permission_id', 'agent_permission', ['agent_id', 'permission_id'], unique=True)
    ### end Alembic commands ###
