"""added audit tables

Revision ID: d27a7ccc0b06
Revises: 9cf6ddb226bd
Create Date: 2016-06-09 15:58:58.921457

"""

# revision identifiers, used by Alembic.
revision = 'd27a7ccc0b06'
down_revision = '9cf6ddb226bd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_vouchers_log_sequence',
    sa.Column('id', mysql.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_vouchers_log',
    sa.Column('auto_id', mysql.BIGINT(), nullable=False),
    sa.Column('change_id', mysql.BIGINT(), nullable=False),
    sa.Column('changed_on', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=True),
    sa.Column('code', sa.VARCHAR(length=200), nullable=False),
    sa.Column('rules', sa.VARCHAR(length=150), nullable=False),
    sa.Column('custom', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('from', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('to', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('schedule', sa.VARCHAR(length=250), nullable=True),
    sa.Column('mutable', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('agent_id', mysql.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('auto_id')
    )
    op.create_index(op.f('ix_all_vouchers_log_code'), 'all_vouchers_log', ['code'], unique=False)
    op.create_index(op.f('ix_all_vouchers_log_change_id'), 'all_vouchers_log', ['change_id'], unique=False)
    op.create_index(op.f('ix_all_vouchers_log_id'), 'all_vouchers_log', ['id'], unique=False)
    op.create_index(op.f('ix_all_vouchers_log_changed_on'), 'all_vouchers_log', ['changed_on'], unique=False)
    op.create_index(op.f('ix_all_vouchers_from'), 'all_vouchers', ['from'], unique=False)
    op.create_index(op.f('ix_all_vouchers_to'), 'all_vouchers', ['to'], unique=False)
    op.create_index('user_voucher_transaction_log_order_id', 'user_voucher_transaction_log', ['order_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_voucher_transaction_log_order_id', table_name='user_voucher_transaction_log')
    op.drop_index(op.f('ix_all_vouchers_to'), table_name='all_vouchers')
    op.drop_index(op.f('ix_all_vouchers_from'), table_name='all_vouchers')
    op.drop_index(op.f('ix_all_vouchers_log_change_id'), table_name='all_vouchers_log')
    op.drop_index(op.f('ix_all_vouchers_log_id'), table_name='all_vouchers_log')
    op.drop_index(op.f('ix_all_vouchers_log_changed_on'), table_name='all_vouchers_log')
    op.drop_index(op.f('ix_all_vouchers_log_code'), table_name='all_vouchers_log')
    op.drop_table('all_vouchers_log')
    op.drop_table('all_vouchers_log_sequence')
    ### end Alembic commands ###
