"""added scheduling

Revision ID: e28f26a063b7
Revises: ba2c62242ecd
Create Date: 2016-04-21 16:14:39.463613

"""

# revision identifiers, used by Alembic.
revision = 'e28f26a063b7'
down_revision = 'ba2c62242ecd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_vouchers', sa.Column('schedule', sa.VARCHAR(length=250), nullable=True))
    op.add_column('vouchers', sa.Column('schedule', sa.VARCHAR(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_vouchers', 'schedule')
    op.drop_column('vouchers', 'schedule')
    ### end Alembic commands ###
