"""added params

Revision ID: f8bc53fa947f
Revises: 7860c3386b2d
Create Date: 2016-06-03 17:07:58.209601

"""

# revision identifiers, used by Alembic.
revision = 'f8bc53fa947f'
down_revision = '7860c3386b2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_tester', sa.Column('params', sa.VARCHAR(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_tester', 'params')
    ### end Alembic commands ###
