"""added colums of session id and user uuid

Revision ID: 24102df3f224
Revises: 31135e47c752
Create Date: 2016-07-04 18:31:25.889271

"""

# revision identifiers, used by Alembic.
revision = '24102df3f224'
down_revision = '31135e47c752'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_voucher_transaction_log', sa.Column('session_id', sa.VARCHAR(length=32), nullable=True))
    op.add_column('user_voucher_transaction_log', sa.Column('user_uuid', sa.VARCHAR(length=32), nullable=True))
    op.add_column('voucher_use_tracker', sa.Column('session_id', sa.VARCHAR(length=32), nullable=True))
    op.add_column('voucher_use_tracker', sa.Column('user_uuid', sa.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher_use_tracker', 'session_id')
    op.drop_column('voucher_use_tracker', 'user_uuid')
    op.drop_column('user_voucher_transaction_log', 'session_id')
    op.drop_column('user_voucher_transaction_log', 'user_uuid')
    ### end Alembic commands ###
