"""fixed indexes

Revision ID: 31135e47c752
Revises: 5fbb77f72fd0
Create Date: 2016-06-10 15:04:50.894806

"""

# revision identifiers, used by Alembic.
revision = '31135e47c752'
down_revision = '5fbb77f72fd0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_permission', 'agent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('agent_permission', 'permission_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    op.drop_index(op.f('ix_permissions_permission'), table_name='permissions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_permissions_permission'), 'permissions', ['permission'], unique=True)
    op.alter_column('agent_permission', 'permission_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.alter_column('agent_permission', 'agent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
