"""changed voucher code from 20 to 200

Revision ID: 31ebbe231b76
Revises: 8c1411c24053
Create Date: 2016-04-04 20:45:26.117275

"""

# revision identifiers, used by Alembic.
revision = '31ebbe231b76'
down_revision = '8c1411c24053'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('all_vouchers', 'code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False,
               nullable=False)
    op.alter_column('vouchers', 'code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vouchers', 'code',
               existing_type=sa.VARCHAR(length=200),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('all_vouchers', 'code',
               existing_type=sa.VARCHAR(length=200),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False,
               nullable=False)
    ### end Alembic commands ###
