"""increased column sizes for auto tester

Revision ID: 3b85516e3d44
Revises: d753f11587b6
Create Date: 2016-06-03 22:23:34.552213

"""

# revision identifiers, used by Alembic.
revision = '3b85516e3d44'
down_revision = 'd753f11587b6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_tester', 'body',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('auto_tester', 'prod_response',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('auto_tester', 'staging_response',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auto_tester', 'staging_response',
               existing_type=sa.VARCHAR(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('auto_tester', 'prod_response',
               existing_type=sa.VARCHAR(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('auto_tester', 'body',
               existing_type=sa.VARCHAR(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
    ### end Alembic commands ###
