"""added tables for audit log

Revision ID: 3df70b4de2b1
Revises: f0212e7ae550
Create Date: 2016-06-09 18:46:13.544352

"""

# revision identifiers, used by Alembic.
revision = '3df70b4de2b1'
down_revision = 'f0212e7ae550'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_vouchers_log_sequence',
    sa.Column('id', mysql.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_vouchers_log',
    sa.Column('auto_id', mysql.BIGINT(), nullable=False),
    sa.Column('change_id', mysql.BIGINT(), nullable=False),
    sa.Column('changed_on', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('id', sa.BINARY(length=16), nullable=True),
    sa.Column('code', sa.VARCHAR(length=200), nullable=False),
    sa.Column('rules', sa.VARCHAR(length=150), nullable=False),
    sa.Column('custom', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('from', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('to', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('schedule', sa.VARCHAR(length=250), nullable=True),
    sa.Column('mutable', mysql.TINYINT(display_width=3, unsigned=True), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=3, unsigned=True), nullable=False),
    sa.Column('type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('agent_id', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['tokens.agent_id'], ),
    sa.PrimaryKeyConstraint('auto_id')
    )
    op.create_index(op.f('ix_all_vouchers_log_code'), 'all_vouchers_log', ['code'], unique=False)
    op.create_index(op.f('ix_all_vouchers_log_from'), 'all_vouchers_log', ['from'], unique=False)
    op.create_index(op.f('ix_all_vouchers_log_id'), 'all_vouchers_log', ['id'], unique=False)
    op.create_index(op.f('ix_all_vouchers_log_to'), 'all_vouchers_log', ['to'], unique=False)
    op.add_column(u'all_vouchers', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.create_index(op.f('ix_all_vouchers_from'), 'all_vouchers', ['from'], unique=False)
    op.create_index(op.f('ix_all_vouchers_to'), 'all_vouchers', ['to'], unique=False)
    op.create_index('user_voucher_transaction_log_order_id', 'user_voucher_transaction_log', ['order_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_voucher_transaction_log_order_id', table_name='user_voucher_transaction_log')
    op.drop_index(op.f('ix_all_vouchers_to'), table_name='all_vouchers')
    op.drop_index(op.f('ix_all_vouchers_from'), table_name='all_vouchers')
    op.drop_column(u'all_vouchers', 'is_active')
    op.drop_index(op.f('ix_all_vouchers_log_to'), table_name='all_vouchers_log')
    op.drop_index(op.f('ix_all_vouchers_log_id'), table_name='all_vouchers_log')
    op.drop_index(op.f('ix_all_vouchers_log_from'), table_name='all_vouchers_log')
    op.drop_index(op.f('ix_all_vouchers_log_code'), table_name='all_vouchers_log')
    op.drop_table('all_vouchers_log')
    op.drop_table('all_vouchers_log_sequence')
    ### end Alembic commands ###
