"""added table for testing

Revision ID: 4603c319a746
Revises: b56a18b1c4df
Create Date: 2016-06-02 18:37:24.775417

"""

# revision identifiers, used by Alembic.
revision = '4603c319a746'
down_revision = 'b56a18b1c4df'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_tester',
    sa.Column('id', mysql.BIGINT(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=250), nullable=False),
    sa.Column('body', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('prod_response', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('staging_response', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('match', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('updated_on', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_tester')
    ### end Alembic commands ###
