"""mysql datetime fsp=6 to support microseconds

Revision ID: 68e7e1dd739d
Revises: 4cc3ff5d232a
Create Date: 2016-04-06 19:46:57.369587

"""

# revision identifiers, used by Alembic.
revision = '68e7e1dd739d'
down_revision = '4cc3ff5d232a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'created_at',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6)
               )
    op.alter_column('tokens', 'last_accessed_at',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6)
               )
    op.alter_column('rule', 'created_at',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('rule', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('vouchers', 'from',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('vouchers', 'to',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('vouchers', 'created_at',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('vouchers', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('all_vouchers', 'from',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('all_vouchers', 'to',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('all_vouchers', 'created_at',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('all_vouchers', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('voucher_use_tracker', 'applied_on',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('user_voucher_transaction_log', 'updated_on',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('auto_freebie_search', 'from',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('auto_freebie_search', 'to',
               existing_type=sa.DATETIME(),
               type_=mysql.DATETIME(fsp=6),
               existing_nullable=False,
               nullable=False
               )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME()
               )
    op.alter_column('tokens', 'last_accessed_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME()
               )
    op.alter_column('rule', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('rule', 'updated_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('vouchers', 'from',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('vouchers', 'to',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('vouchers', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('vouchers', 'updated_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('all_vouchers', 'from',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('all_vouchers', 'to',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('all_vouchers', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('all_vouchers', 'updated_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('voucher_use_tracker', 'applied_on',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('user_voucher_transaction_log', 'updated_on',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('auto_freebie_search', 'from',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    op.alter_column('auto_freebie_search', 'to',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.DATETIME(),
               existing_nullable=False,
               nullable=False
               )
    ### end Alembic commands ###
