"""change table name

Revision ID: b56a18b1c4df
Revises: 6ad24a69e213
Create Date: 2016-05-17 15:33:39.301037

"""

# revision identifiers, used by Alembic.
revision = 'b56a18b1c4df'
down_revision = '6ad24a69e213'

from alembic import op

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('auto_freebie_search', 'auto_benefits')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('auto_benefits', 'auto_freebie_search')
    ### end Alembic commands ###
