"""added epired_at in all_vouchers

Revision ID: bbd11511743f
Revises: 370934469103
Create Date: 2016-04-02 00:34:28.180700

"""

# revision identifiers, used by Alembic.
revision = 'bbd11511743f'
down_revision = '370934469103'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_vouchers', sa.Column('expired_at', sa.DATETIME(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_vouchers', 'expired_at')
    ### end Alembic commands ###
