"""added params

Revision ID: d753f11587b6
Revises: 4603c319a746
Create Date: 2016-06-03 17:04:19.623224

"""

# revision identifiers, used by Alembic.
revision = 'd753f11587b6'
down_revision = '4603c319a746'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_tester', sa.Column('params', sa.VARCHAR(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_tester', 'params')
    ### end Alembic commands ###
