"""added varchar columns back

Revision ID: f0212e7ae550
Revises: 21c7f528e703
Create Date: 2016-06-06 14:49:30.561363

"""

# revision identifiers, used by Alembic.
revision = 'f0212e7ae550'
down_revision = '21c7f528e703'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_tester', sa.Column('body_varchar', sa.VARCHAR(length=5000), nullable=True))
    op.add_column('auto_tester', sa.Column('prod_response_varchar', sa.VARCHAR(length=5000), nullable=True))
    op.add_column('auto_tester', sa.Column('staging_response_varchar', sa.VARCHAR(length=5000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_tester', 'staging_response_varchar')
    op.drop_column('auto_tester', 'prod_response_varchar')
    op.drop_column('auto_tester', 'body_varchar')
    ### end Alembic commands ###
