"""initial migration

Revision ID: 0b173a10806b
Revises: None
Create Date: 2016-04-01 00:58:36.790693

"""

# revision identifiers, used by Alembic.
revision = '0b173a10806b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_vouchers',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rules', sa.VARCHAR(length=150), nullable=False),
    sa.Column('custom', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('from', sa.DATETIME(), nullable=True),
    sa.Column('to', sa.DATETIME(), nullable=True),
    sa.Column('mutable', sa.BOOLEAN(), nullable=True),
    sa.Column('type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('criteria_json', sa.VARCHAR(length=8000), nullable=False),
    sa.Column('benefits_json', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('sha2hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_sha2hash'), 'rule', ['sha2hash'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rules', sa.VARCHAR(length=150), nullable=False),
    sa.Column('custom', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('from', sa.DATETIME(), nullable=True),
    sa.Column('to', sa.DATETIME(), nullable=True),
    sa.Column('mutable', sa.BOOLEAN(), nullable=True),
    sa.Column('type', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('auto_freebie_search',
    sa.Column('id', mysql.BIGINT(), nullable=False),
    sa.Column('type', mysql.INTEGER(), nullable=False),
    sa.Column('variants', mysql.INTEGER(), nullable=True),
    sa.Column('zone', mysql.INTEGER(), nullable=False),
    sa.Column('range_min', mysql.INTEGER(), nullable=True),
    sa.Column('range_max', mysql.INTEGER(), nullable=True),
    sa.Column('cart_range_min', mysql.INTEGER(), nullable=True),
    sa.Column('cart_range_max', mysql.INTEGER(), nullable=True),
    sa.Column('voucher_id', sa.BINARY(length=16), nullable=False),
    sa.Column('from', sa.DATETIME(), nullable=False),
    sa.Column('to', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['all_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_freebie_search_cart_range_max'), 'auto_freebie_search', ['cart_range_max'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_cart_range_min'), 'auto_freebie_search', ['cart_range_min'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_from'), 'auto_freebie_search', ['from'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_range_max'), 'auto_freebie_search', ['range_max'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_range_min'), 'auto_freebie_search', ['range_min'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_to'), 'auto_freebie_search', ['to'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_type'), 'auto_freebie_search', ['type'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_variants'), 'auto_freebie_search', ['variants'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_voucher_id'), 'auto_freebie_search', ['voucher_id'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_zone'), 'auto_freebie_search', ['zone'], unique=False)
    op.create_table('user_voucher_transaction_log',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('updated_on', sa.DATETIME(), nullable=False),
    sa.Column('voucher_id', sa.BINARY(length=16), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', mysql.TINYINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['all_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher_use_tracker',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('applied_on', sa.DATETIME(), nullable=False),
    sa.Column('voucher_id', sa.BINARY(length=16), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['all_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voucher_use_tracker')
    op.drop_table('user_voucher_transaction_log')
    op.drop_index(op.f('ix_auto_freebie_search_zone'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_voucher_id'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_variants'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_type'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_to'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_range_min'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_range_max'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_from'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_cart_range_min'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_cart_range_max'), table_name='auto_freebie_search')
    op.drop_table('auto_freebie_search')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_rule_sha2hash'), table_name='rule')
    op.drop_table('rule')
    op.drop_table('all_vouchers')
    ### end Alembic commands ###
