"""api tokens

Revision ID: 370934469103
Revises: 0b173a10806b
Create Date: 2016-04-01 14:25:56.243506

"""

# revision identifiers, used by Alembic.
revision = '370934469103'
down_revision = '0b173a10806b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token', sa.VARCHAR(length=250), nullable=False),
    sa.Column('agent_id', mysql.INTEGER(), nullable=False),
    sa.Column('agent_name', sa.VARCHAR(length=250), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_accessed_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_tokens_agent_id'), 'tokens', ['agent_id'], unique=True)
    op.add_column(u'all_vouchers', sa.Column('agent_id', mysql.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'all_vouchers', 'tokens', ['agent_id'], ['agent_id'])
    op.add_column(u'auto_freebie_search', sa.Column('agent_id', mysql.INTEGER(), nullable=True))
    op.create_index(op.f('ix_auto_freebie_search_cart_range_max'), 'auto_freebie_search', ['cart_range_max'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_cart_range_min'), 'auto_freebie_search', ['cart_range_min'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_from'), 'auto_freebie_search', ['from'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_range_max'), 'auto_freebie_search', ['range_max'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_range_min'), 'auto_freebie_search', ['range_min'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_to'), 'auto_freebie_search', ['to'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_type'), 'auto_freebie_search', ['type'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_variants'), 'auto_freebie_search', ['variants'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_voucher_id'), 'auto_freebie_search', ['voucher_id'], unique=False)
    op.create_index(op.f('ix_auto_freebie_search_zone'), 'auto_freebie_search', ['zone'], unique=False)
    op.create_foreign_key(None, 'auto_freebie_search', 'tokens', ['agent_id'], ['agent_id'])
    op.add_column(u'rule', sa.Column('agent_id', mysql.INTEGER(), nullable=True))
    op.create_index(op.f('ix_rule_sha2hash'), 'rule', ['sha2hash'], unique=False)
    op.create_foreign_key(None, 'rule', 'tokens', ['agent_id'], ['agent_id'])
    op.add_column(u'user_voucher_transaction_log', sa.Column('agent_id', mysql.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'user_voucher_transaction_log', 'tokens', ['agent_id'], ['agent_id'])
    op.add_column(u'voucher_use_tracker', sa.Column('agent_id', mysql.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'voucher_use_tracker', 'tokens', ['agent_id'], ['agent_id'])
    op.add_column(u'vouchers', sa.Column('agent_id', mysql.INTEGER(), nullable=True))
    op.create_unique_constraint(None, 'vouchers', ['id'])
    op.create_foreign_key(None, 'vouchers', 'tokens', ['agent_id'], ['agent_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vouchers', type_='foreignkey')
    op.drop_constraint(None, 'vouchers', type_='unique')
    op.drop_column(u'vouchers', 'agent_id')
    op.drop_constraint(None, 'voucher_use_tracker', type_='foreignkey')
    op.drop_column(u'voucher_use_tracker', 'agent_id')
    op.drop_constraint(None, 'user_voucher_transaction_log', type_='foreignkey')
    op.drop_column(u'user_voucher_transaction_log', 'agent_id')
    op.drop_constraint(None, 'rule', type_='foreignkey')
    op.drop_index(op.f('ix_rule_sha2hash'), table_name='rule')
    op.drop_column(u'rule', 'agent_id')
    op.drop_constraint(None, 'auto_freebie_search', type_='foreignkey')
    op.drop_index(op.f('ix_auto_freebie_search_zone'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_voucher_id'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_variants'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_type'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_to'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_range_min'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_range_max'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_from'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_cart_range_min'), table_name='auto_freebie_search')
    op.drop_index(op.f('ix_auto_freebie_search_cart_range_max'), table_name='auto_freebie_search')
    op.drop_column(u'auto_freebie_search', 'agent_id')
    op.drop_constraint(None, 'all_vouchers', type_='foreignkey')
    op.drop_column(u'all_vouchers', 'agent_id')
    op.drop_index(op.f('ix_tokens_agent_id'), table_name='tokens')
    op.drop_table('tokens')
    ### end Alembic commands ###
