"""changed agentid to string

Revision ID: ba2c62242ecd
Revises: 523481691123
Create Date: 2016-04-15 14:41:52.857489

"""

# revision identifiers, used by Alembic.
revision = 'ba2c62242ecd'
down_revision = '523481691123'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tokens_agent_name'), 'tokens', ['agent_name'], unique=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_agent_name'), table_name='tokens')
    ### end Alembic commands ###
