mysql:
    connection: mysql+pymysql://root:root@localhost/coupons

logfile: "CouponService.out"
errorlogfile: "CouponServiceError.log"
debug: True

ruleredis:
    host: localhost
    port: 6379
    db: 0