port: 8001

mysql:
    connection: mysql+pymysql://root:root@localhost/coupons

logfile:
    foldername: couponlogs
    logfilename: CouponService.out
    errorlogfilename: CouponServiceError.log

debug: True

ruleredis:
    host: localhost
    port: 6379
    db: 0

informationhosturl: http://uatadmin.api.askmegrocery.com

subscriptionendpoint: /item/

locationendpoint: /area/

userendpoint: /user/id/

token: Z3IwY2VyeTpncjBjZXJ5QDIx