mysql:
    connection: mysql+pymysql://root:root@localhost/coupons

logfile:
    foldername: logs
    logfilename: CouponService.out
    errorlogfilename: CouponServiceError.log

debug: True

ruleredis:
    host: localhost
    port: 6379
    db: 0