port: 8000

mysql:
    connection: mysql+pymysql://coupon:coupon1234@coupon.c0wj8qdslqom.ap-southeast-1.rds.amazonaws.com/coupon

logfile:
    foldername: couponlogs
    logfilename: CouponService.out
    errorlogfilename: CouponServiceError.log

debug: True

ruleredis:
    host: coupon.6h3jqd.0001.apse1.cache.amazonaws.com
    port: 6379
    db: 0

informationhosturl: http://uatadmin.api.askmegrocery.com

subscriptionendpoint: /item/

locationendpoint: /area/

userendpoint: /user/id/

token: Z3IwY2VyeTpncjBjZXJ5QDIx