mysql:
    connection: mysql+pymysql://root:root@localhost/coupons_test

logfile:
    foldername: logs
    logfilename: CouponServiceTest.out
    errorlogfilename: CouponServiceTestError.log
debug: True

ruleredis:
    host: localhost
    port: 6379
    db: 0