mysql:
    connection: mysql+pymysql://root:root@localhost/coupons_test

logfile: "CouponServiceTest.out"
errorlogfile: "CouponServiceTestError.log"
debug: True

ruleredis:
    host: localhost
    port: 6379
    db: 0