port: 8000

mysql:
    connection: mysql+pymysql://coupon:coupon1234@coupon.c0wj8qdslqom.ap-southeast-1.rds.amazonaws.com/new_grocery_coupons

logfile:
    logfilename: CouponService.out
    errorlogfilename: CouponServiceError.log

debug: True

ruleredis:
    host: coupon.6h3jqd.0001.apse1.cache.amazonaws.com
    port: 6379
    db: 0

kafka:
  host: 'kafka01.production.askmebazaar.com:9092,kafka02.production.askmebazaar.com:9092,kafka03.production.askmebazaar.com:9092'
  zookeeper: 'kafka01.production.askmebazaar.com:2181,kafka02.production.askmebazaar.com:2181,kafka03.production.askmebazaar.com:2181'

subscriptionendpoint: http://pyservice01.staging.askme.com:9070/v1/search

subscriptionheaders: {Content-Type: application/json}

locationendpoint: http://pyservice01.staging.askme.com:8080/geo/v2.0/get_by_gid?gids=

userendpoint: http://pyservice01.staging.askme.com:9880/orderapi/v1/user

userphonenoapi: http://pyservice01.staging.askme.com:9095/users/v2/user/

userphoneapiheaders: {Content-Type: application/json, clientid: 960AF3923F5711E68287066A28C33ECE, secret: 960AFAAE3F5711E68287066A28C33ECE, Authorization: abcdefghijklmnopqrstuvwxyz}

migrationsdirectory: new_grocery_migrations

testtoken:
  user: autotest
  token: autotest
  kafkatopic: new_grocery_prod_replay
  hosttohit: http://localhost:8001
  pushtokafka: no