port: 8000

mysql:
    connection: mysql+pymysql://root:root@localhost/coupons_test

logfile:
    logfilename: CouponServiceTest.out
    errorlogfilename: CouponServiceTestError.log
debug: True

ruleredis:
    host: localhost
    port: 6379
    db: 0


subscriptionendpoint: http://pyservice01.staging.askme.com:9070/v1/search

subscriptionheaders: {Content-Type: application/json}

locationendpoint: http://pyservice01.staging.askme.com:8080/geo/v2.0/get_by_gid?gids=

userendpoint: http://pyservice01.staging.askme.com:9880/orderapi/v1/user/

migrationsdirectory: new_grocery_migrations