port: 8001

mysql:
    connection: mysql+pymysql://root:root@localhost/coupons

logfile:
    logfilename: CouponService.out
    errorlogfilename: CouponServiceError.log

debug: True

ruleredis:
    host: localhost
    port: 6379
    db: 0

kafka:
  host: localhost:9092

informationhosturl: http://uatadmin.api.askmegrocery.com

subscriptionendpoint: /item/

locationendpoint: /area/

userendpoint: /user/id/

userfromphoneendpoint: /user/mobile/

token: Z3IwY2VyeTpncjBjZXJ5QDIx

migrationsdirectory: old_grocery_migrations

test