port: 8000

mysql:
    connection: mysql+pymysql://grocery:grocery1234@grocery.c0wj8qdslqom.ap-southeast-1.rds.amazonaws.com:3306/grocery

logfile:
    logfilename: CouponService.out
    errorlogfilename: CouponServiceError.log

debug: True

ruleredis:
    host: grocery.6h3jqd.0001.apse1.cache.amazonaws.com
    port: 6379
    db: 0

kafka:
  host: 'kafka01.production.askmebazaar.com:9092,kafka02.production.askmebazaar.com:9092,kafka03.production.askmebazaar.com:9092'
  zookeeper: 'kafka01.production.askmebazaar.com:2181,kafka02.production.askmebazaar.com:2181,kafka03.production.askmebazaar.com:2181'

informationhosturl: http://admin.api.askmegrocery.com

subscriptionendpoint: /services.ashx?method=getitembyid&itemid=

locationendpoint: /area/

userendpoint: /user/id/

userfromphoneendpoint: /user/mobile/

token: Z3IwY2VyeTpncjBjZXJ5QDIx

migrationsdirectory: old_grocery_migrations

testtoken:
  user: autotest
  token: autotest
  kafkatopic: coupons_grocery_preprod_testing
  hosttohit: http://pyservice01.staging.askme.com:9933
  pushtokafka: no