port: 8000

mysql:
    connection: mysql+pymysql://grocery:grocery1234@grocery.c0wj8qdslqom.ap-southeast-1.rds.amazonaws.com:3306/grocery

logfile:
    logfilename: CouponService.out
    errorlogfilename: CouponServiceError.log

debug: True

ruleredis:
    host: grocery.6h3jqd.0001.apse1.cache.amazonaws.com
    port: 6379
    db: 0

informationhosturl: http://admin.api.askmegrocery.com

subscriptionendpoint: /item/

locationendpoint: /area/

userendpoint: /user/id/

userfromphoneendpoint: /user/mobile/

token: Z3IwY2VyeTpncjBjZXJ5QDIx

migrationsdirectory: old_grocery_migrations