port: 8000

mysql:
    connection: mysql+pymysql://root:root@localhost/coupons_test

logfile:
    logfilename: CouponServiceTest.out
    errorlogfilename: CouponServiceTestError.log
debug: True

ruleredis:
    host: localhost
    port: 6379
    db: 0

kafka:
  host: localhost:9092
  zookeeper: localhost:2181

informationhosturl: http://uatadmin.api.askmegrocery.com

subscriptionendpoint: /services.ashx?method=getitembyid&itemid=

locationendpoint: /area/

userendpoint: /user/id/

userfromphoneendpoint: /user/mobile/

token: Z3IwY2VyeTpncjBjZXJ5QDIx

migrationsdirectory: old_grocery_migrations

testtoken:
  user: autotest
  token: autotest
  kafkatopic: new_grocery_prod_replay
  hosttohit: http://localhost:8001
  pushtokafka: no
